inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('list-suppliers/',views.list_suppliers,name='list_suppliers'),
    path('add-supplier/',views.add_supplier,name='add_supplier'),
    path('update-supplier/<int:supplier_id>/', views.update_supplier, name='update_supplier'),
    path('delete-supplier/<int:supplier_id>/',views.delete_supplier,name='delete_supplier'),
    # stock
    path('add-stock/<int:product_id>/',views.add_product_stock,name='add_product_stock'),
]

store/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('profiles.urls','profiles'),namespace='profiles')),
    path('',include(('products.urls','products'),namespace='products')),
    path('',include(('inventory.urls','inventory'),namespace='inventory')),
]

inventory/models.py
from django.db import models
from products.models import Product
from django.db.models.signals import pre_save
from django.dispatch import receiver

class ProductSupplier(models.Model):
    supplier_name = models.CharField(max_length=150,unique=True)
    supplier_description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('date_created',)
        verbose_name = 'Supplier'
        verbose_name_plural = 'Suppliers'
    def __str__(self):
        return self.supplier_name


class ProductStock(models.Model):
    product_supplier = models.ForeignKey(ProductSupplier,related_name='supplier',on_delete=models.CASCADE)
    product = models.ForeignKey(Product,related_name='stock',on_delete=models.CASCADE)
    product_quantity = models.IntegerField()
    products_issued = models.IntegerField(default=0)
    product_bought_at = models.DecimalField(max_digits=10, decimal_places=2)
    stock_finished = models.BooleanField(default=False)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    
    class Meta:
        ordering = ('-date_created',)
        verbose_name = 'Product Stock'
        verbose_name_plural = 'Product Stocks'
    
    def __str__(self):
        return self.product.product_name
    
    def update_stock_finished(self):
        if self.products_issued >= self.product_quantity:
            self.stock_finished = True
        else:
            self.stock_finished = False
    
    def save(self, *args, **kwargs):
        self.update_stock_finished()
        super().save(*args, **kwargs)
    
    def product_stock_amount(self):
        return self.product_bought_at * self.product_quantity

@receiver(pre_save, sender=ProductStock)
def update_stock_finished(sender, instance, **kwargs):
    instance.update_stock_finished()

inventory/forms.py
from django import forms
from .models import ProductSupplier,ProductStock

class ProductSupplierForm(forms.ModelForm):
    class Meta:
        model = ProductSupplier
        fields = ['supplier_name', 'supplier_description']

class ProductStockForm(forms.ModelForm):
    class Meta:
        model = ProductStock
        fields = ['product_supplier','product_quantity','product_bought_at',]

inventory/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from products.models import Product
from .models import ProductSupplier, ProductStock
from .forms import ProductSupplierForm, ProductStockForm  # Create a form for adding categories

@login_required(login_url='/')
def list_suppliers(request):
    suppliers = ProductSupplier.objects.all()
    return render(request, 'inventory/list_suppliers.html', {'suppliers': suppliers})

@login_required(login_url='/')
def add_supplier(request):
    if request.method == 'POST':
        form = ProductSupplierForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('inventory:list_suppliers')
    else:
        form = ProductSupplierForm()
    return render(request, 'inventory/add_supplier.html', {'form': form})

@login_required(login_url='/')
def update_supplier(request, supplier_id):
    supplier = get_object_or_404(ProductSupplier, pk=supplier_id)
    if request.method == 'POST':
        form = ProductSupplierForm(request.POST, instance=supplier)
        if form.is_valid():
            form.save()
            return redirect('inventory:list_suppliers')
    else:
        form = ProductSupplierForm(instance=supplier)
    return render(request, 'inventory/update_supplier.html', {'form': form, 'supplier': supplier})

@login_required(login_url='/')
def delete_supplier(request, supplier_id):
    supplier = get_object_or_404(ProductSupplier, pk=supplier_id)
    supplier.delete()
    return redirect('inventory:list_suppliers')

@login_required(login_url='/')
def add_product_stock(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductStockForm(request.POST)
        if form.is_valid():
            product_stock = form.save(commit=False)
            product_stock.product = product  # Assign the product to the ProductStock instance
            product_stock.save()  # Save the ProductStock with the associated product
            return redirect('products:list_products')
    else:
        form = ProductStockForm()
    return render(request, 'inventory/add_stock.html', {'form': form})

inventory/templates/inventory/add_stock.html
{% extends "products/base.html" %}
{% block title %}
    Add Stock
{% endblock %}
{% block content %}
<div class="container">
    <h2>Add Stock</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.product_supplier.label_tag }}
            {{ form.product_supplier }}
        </div>
        <div class="form-group">
            {{ form.product_quantity.label_tag }}
            {{ form.product_quantity }}
        </div>
        <div class="form-group">
            {{ form.product_bought_at.label_tag }}
            {{ form.product_bought_at }}
        </div>
        <button type="submit" class="btn btn-primary">Add Stock</button>
    </form>
</div>
{% endblock %}

inventory/templates/inventory/add_supplier.html
{% extends "products/base.html" %}
{% block title %}
    Add Supplier
{% endblock %}
{% block content %}
<div class="container">
    <h2>Add Supplier</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.supplier_name.label_tag }}
            {{ form.supplier_name }}
        </div>
        <div class="form-group">
            {{ form.supplier_description.label_tag }}
            {{ form.supplier_description }}
        </div>
        <button type="submit" class="btn btn-primary">Add Supplier</button>
    </form>
</div>
{% endblock %}

inventory/templates/inventory/list_suppliers.html
{% extends "products/base.html" %}
{% block title %}
    Suppliers
{% endblock %}
{% block content %}
<div class="container">
    <h2>Suppliers List</h2>
    <div>
        <a href="{% url 'inventory:add_supplier'%}" class="btn btn-primary">Add Supplier</a>
    <div>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Supplier Name</th>
                <th>Supplier Description</th>
                <th> Update </th>
            </tr>
        </thead>
        <tbody>
            {% for supplier in suppliers %}
                <tr>
                    <td>{{ supplier.supplier_name }}</td>
                    <td>{{ supplier.supplier_description }} <br>
                        <a href="{% url 'inventory:update_supplier' supplier.id %}" class="btn btn-primary">Update</a>
                    </td>
                    <td><a href="{% url 'inventory:delete_supplier' supplier.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock%}

inventory/templates/inventory/update_supplier.html
{% extends "products/base.html" %}
{% block title %}
    Update Supplier
{% endblock %}
{% block content %}
<div class="container">
    <h2>Update Supplier</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.supplier_name.label_tag }}
            {{ form.supplier_name }}
        </div>
        <div class="form-group">
            {{ form.supplier_description.label_tag }}
            {{ form.supplier_description }}
        </div>
        <button type="submit" class="btn btn-primary">Update Supplier</button>
    </form>
</div>
{% endblock%}