inventory/urls.py
from django.urls import path
from . import views

app_name = 'inventory'
urlpatterns = [
    path('list-suppliers/',views.list_suppliers,name='list_suppliers'),
    path('add-supplier/',views.add_supplier,name='add_supplier'),
    path('update-supplier/<int:supplier_id>/', views.update_supplier, name='update_supplier'),
    path('delete-supplier/<int:supplier_id>/',views.delete_supplier,name='delete_supplier'),
    # stock
    path('add-stock/<int:product_id>/',views.add_product_stock,name='add_product_stock'),
]

products/urls.py
from django.urls import path
from . import views

app_name = 'products'
urlpatterns = [
    path('',views.index,name='index'),
    path('list-category/',views.list_categories,name='list_categories'),
    path('add-category/',views.add_category,name='add_category'),
    path('update-category/<int:category_id>/', views.update_category, name='update_category'),
    path('delete-category/<int:category_id>/',views.delete_category,name='delete_category'),
    # products
    path('list-product/',views.list_products,name='list_products'),
    path('add-product/',views.add_product,name='add_product'),
    path('update-product/<int:product_id>/', views.update_product, name='update_product'),
    path('delete-product/<int:product_id>/',views.delete_product,name='delete_product'),
    path('detail/<int:product_id>/',views.product_detail,name='product_detail'),
]

profiles/urls.py
from django.urls import path
from . import views

app_name = 'profiles'
urlpatterns = [
    path('user-register/',views.user_register,name='user_register'),
    path('log-in/',views.log_in,name='log_in'),
]

store/urls.py
from django.contrib import admin
from django.urls import path,include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('',include(('profiles.urls','profiles'),namespace='profiles')),
    path('',include(('products.urls','products'),namespace='products')),
    path('',include(('inventory.urls','inventory'),namespace='inventory')),
]

products/models.py
from django.db import models
from django.urls import reverse
from django.utils.text import slugify
from django.db.models import F,Sum
from decimal import Decimal

class Category(models.Model):
    # Description of a product. Fertilizer, feeds, etc.
    category_name = models.CharField(max_length=100,db_index=True)
    category_slug = models.SlugField(max_length=110,db_index=True,unique=True)
    category_description = models.TextField()
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)
    class Meta:
        ordering = ('category_name',)
        verbose_name = 'Category'
        verbose_name_plural = 'Categories'
    def __str__(self):
        return self.category_name
    
    def save(self, *args, **kwargs):
        self.category_slug = slugify(self.category_name)
        super(Category, self).save(*args, **kwargs)

class Product(models.Model):
    product_category = models.ForeignKey(Category,related_name='products',on_delete=models.CASCADE)
    product_code = models.CharField(max_length=20, db_index=True, unique=True)
    product_name = models.CharField(max_length=100, db_index=True)
    product_slug = models.SlugField(max_length=110, db_index=True)
    product_description = models.TextField(blank=True)
    date_created = models.DateTimeField(auto_now_add=True)
    date_updated = models.DateTimeField(auto_now=True)

    class Meta:
        ordering = ('product_name',)
        index_together = (('id', 'product_slug'),)
    def __str__(self):
        return self.product_name
    
    def save(self, *args, **kwargs):
        self.product_slug = slugify(self.product_name)
        super(Product, self).save(*args, **kwargs)
    
    def get_total_stock_quantity(self):
        total_quantity = 0

        # Calculate the total stock quantity for the product
        product_stocks = self.stock.all()  # Assuming you have related_name='stock' in ProductStock
        for stock in product_stocks:
            total_quantity += stock.product_quantity

        return total_quantity

    def get_remaining_stock(self):
        total_quantity = self.get_total_stock_quantity()
        products_issued_sum = self.stock.aggregate(Sum('products_issued'))['products_issued__sum']
        remaining_stock = total_quantity - products_issued_sum

        return remaining_stock
    
    def calculate_total_stock_value(self):
        total_stock_value = 0

        for product_stock in self.stock.all():
            remaining_stock = product_stock.product_quantity - product_stock.products_issued
            stock_value = remaining_stock * product_stock.product_bought_at
            total_stock_value += stock_value

        return total_stock_value

products/forms.py
from django import forms
from .models import Category,Product

class CategoryForm(forms.ModelForm):
    class Meta:
        model = Category
        fields = ['category_name', 'category_description']

class ProductForm(forms.ModelForm):
    class Meta:
        model = Product
        fields = ['product_category','product_code','product_name','product_description']

products/views.py
from django.shortcuts import render, redirect,get_object_or_404
from django.contrib.auth.decorators import login_required
from inventory.models import ProductStock
from .models import Category, Product
from .forms import CategoryForm, ProductForm  # Create a form for adding categories

@login_required(login_url='/')
def list_categories(request):
    categories = Category.objects.all()
    return render(request, 'products/list_categories.html', {'categories': categories})

@login_required(login_url='/')
def add_category(request):
    if request.method == 'POST':
        form = CategoryForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:list_categories')
    else:
        form = CategoryForm()
    return render(request, 'products/add_category.html', {'form': form})

@login_required(login_url='/')
def update_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    if request.method == 'POST':
        form = CategoryForm(request.POST, instance=category)
        if form.is_valid():
            form.save()
            return redirect('products:list_categories')
    else:
        form = CategoryForm(instance=category)
    return render(request, 'products/update_category.html', {'form': form, 'category': category})

@login_required(login_url='/')
def delete_category(request, category_id):
    category = get_object_or_404(Category, pk=category_id)
    category.delete()
    return redirect('products:list_categories')

@login_required(login_url='/')
def list_products(request):
    products = Product.objects.all()
    return render(request, 'products/list_products.html', {'products': products})

@login_required(login_url='/')
def add_product(request):
    if request.method == 'POST':
        form = ProductForm(request.POST)
        if form.is_valid():
            form.save()
            return redirect('products:list_products')
    else:
        form = ProductForm()
    return render(request, 'products/add_product.html', {'form': form})

@login_required(login_url='/')
def update_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    if request.method == 'POST':
        form = ProductForm(request.POST, instance=product)
        if form.is_valid():
            form.save()
            return redirect('products:list_products')
    else:
        form = ProductForm(instance=product)
    return render(request, 'products/update_product.html', {'form': form, 'product': product})

@login_required(login_url='/')
def delete_product(request, product_id):
    product = get_object_or_404(Product, pk=product_id)
    product.delete()
    return redirect('products:list_products')

@login_required(login_url='/')
def product_detail(request,product_id):
    product = get_object_or_404(Product, pk=product_id)
    stocks = ProductStock.objects.filter(product=product,stock_finished=False)
    return render(request, 'products/product_detail.html', {'product': product,'stocks':stocks})

def index(request):
    return render(request, 'products/index.html')
    

products/templates/products/add_category.html
{% extends "products/base.html" %}
{% block title %}
    Add Category
{% endblock %}
{% block content %}
<div class="container">
    <h2>Add Category</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.category_name.label_tag }}
            {{ form.category_name }}
        </div>
        <div class="form-group">
            {{ form.category_description.label_tag }}
            {{ form.category_description }}
        </div>
        <button type="submit" class="btn btn-primary">Add Category</button>
    </form>
</div>
{% endblock%}

products/templates/products/add_product.html
{% extends "products/base.html" %}
{% block title %}
    Add Product
{% endblock %}
{% block content %}
<div class="container">
    <h2>Add Product</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.product_category.label_tag }}
            {{ form.product_category }}
        </div>
        <div class="form-group">
            {{ form.product_code.label_tag }}
            {{ form.product_code }}
        </div>
        <div class="form-group">
            {{ form.product_name.label_tag }}
            {{ form.product_name }}
        </div>
        <div class="form-group">
            {{ form.product_description.label_tag }}
            {{ form.product_description }}
        </div>
        <button type="submit" class="btn btn-primary">Add Product</button>
    </form>
</div>
{% endblock %}

products/templates/products/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>{% block title %}Store{% endblock %}</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body class="container-fluid">
    <div style="padding-top: 15px;">
    <!-- Start of Nav-->
    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
        <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'products:index'%}">Home</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarNavDropdown">
            <ul class="navbar-nav">
                <li class="nav-item"><a class="nav-link" href="{% url 'products:list_products'%}">Products</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'products:list_categories'%}">Categories</a></li>
                <li class="nav-item"><a class="nav-link" href="{% url 'inventory:list_suppliers'%}">Suppliers</a></li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                    Profiles
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                        <li><a class="dropdown-item" href="{% url 'profiles:user_register'%}">Sign Up</a></li>
                        <li><a class="dropdown-item" href="{% url 'profiles:log_in' %}">Log In</a></li>
                    </ul>
                </li>
            </ul>
        </div>
        </div>
    </nav>
    <!-- End of Nav-->
    </div>
    <div id="content";class="container-fluid">
        {% block content %}
        {% endblock %}
        
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

products/templates/products/index.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Store Management</title>
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-rbsA2VBKQhggwzxH7pPCaAqO46MgnOM80zW1RWuH61DGLwZJEdK2Kadq2F9CUG65" crossorigin="anonymous">
</head>
<body class="container-fluid">
    <div style="padding-top: 15px;">
        <!-- Start of Nav-->
        <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e3f2fd;">
            <div class="container-fluid">
                <a class="navbar-brand" href="#">Home</a>
                <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavDropdown" aria-controls="navbarNavDropdown" aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="collapse navbar-collapse" id="navbarNavDropdown">
                    <ul class="navbar-nav">
                        <li class="nav-item"><a class="nav-link" href="{% url 'products:list_products' %}">Products</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'products:list_categories' %}">Categories</a></li>
                        <li class="nav-item"><a class="nav-link" href="{% url 'inventory:list_suppliers' %}">Suppliers</a></li>
                        <li class="nav-item dropdown">
                            <a class="nav-link dropdown-toggle" href="#" id="navbarDropdownMenuLink" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                            Profiles
                            </a>
                            <ul class="dropdown-menu" aria-labelledby="navbarDropdownMenuLink">
                                <li><a class="dropdown-item" href="{% url 'profiles:user_register'%}">Sign Up</a></li>
                                <li><a class="dropdown-item" href="{% url 'profiles:log_in' %}">Log In</a></li>
                            </ul>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
        <!-- End of Nav-->
    </div>
    <div class="container mt-5">
        <h1>Welcome to the Store Management Application</h1>
        <p>This simple web application allows you to manage your store effectively. You can perform the following functionalities:</p>
        <ul>
            <li>Sign up</li>
            <li>Log in </li>
            <li>Create product in stock</li>
            <li>View Product details</li>
            <li>Delete Product in stock</li>
            <li>Update the Product details</li>
        </ul>
        <p>Explore the menu options above to get started.</p>
    </div>
    <!-- Option 1: Bootstrap Bundle with Popper -->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-MrcW6ZMFYlzcLA8Nl+NtUVF0sA7MsXsP1UyJoMp4YLEuNSfAP+JcXn/tWtIaxVXM" crossorigin="anonymous"></script>
</body>
</html>

products/templates/products/list_categories.html
{% extends "products/base.html" %}
{% block title %}
    Categories
{% endblock %}
{% block content %}
<div class="container">
    <h2>List Categories</h2>
    <div>
        <a href="{% url 'products:add_category'%}" class="btn btn-primary">Add Category</a>
    <div>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Category Name</th>
                <th>Category Description</th>
                <th> Update </th>
            </tr>
        </thead>
        <tbody>
            {% for category in categories %}
                <tr>
                    <td>{{ category.category_name }}</td>
                    <td>{{ category.category_description }} <br>
                        <a href="{% url 'products:update_category' category.id %}" class="btn btn-primary">Update</a>
                    </td>
                    <td><a href="{% url 'products:delete_category' category.id %}" class="btn btn-danger">Delete</a></td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

products/templates/products/list_products.html
{% extends "products/base.html" %}
{% block title %}
    Products
{% endblock %}
{% block content %}
<div class="container">
    <h2>Product List</h2>
    <div>
        <a href="{% url 'products:add_product'%}" class="btn btn-primary">Add Product</a>
    <div>
    <br>
    <table class="table table-bordered">
        <thead>
            <tr>
                <th>Product Name</th>
                <th>Remaining Stock</th>
                <th>Product Category</th>
                <th>Stock Value</th>
                <th> Action </th>
            </tr>
        </thead>
        <tbody>
            {% for product in products %}
                <tr>
                    <td>
                        {{ product.product_name }}<br>
                        <a href="{% url 'products:product_detail' product.id %}" class="text-decoration-none">View Details</a>
                    </td>
                    <td>
                        {{product.get_remaining_stock}}<br>
                        <a href="{% url 'inventory:add_product_stock' product.id %}" class="text-decoration-none">Add Stock</a>
                    </td>
                    <td>{{ product.product_category }}</td>
                    <td>{{product.calculate_total_stock_value}}</td>
                    <td>
                        <a href="{% url 'products:update_product' product.id %}" class="text-decoration-none"><mark>Update Product Details</mark></a> <br><br>
                        <a href="{% url 'products:delete_product' product.id %}" class="text-decoration-none"><mark class="bg-danger text-green">Delete Product</mark></a>
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
</div>
{% endblock %}

products/templates/products/product_detail.html
{% extends "products/base.html" %}
{% block title %}
    {{product.product_name}}
{% endblock %}
{% block content %}
<div class="container">
    <div class="row">
        <div class="col-md-6">
            <h2>{{ product.product_name }}</h2>
            <p>
                <strong>Category:</strong> {{ product.product_category }}
            </p>
            <p>
                <strong>Product Code:</strong> {{ product.product_code }}
            </p>
            <p>
                <strong>Remaining Stock:</strong> {{ product.get_remaining_stock }}
            </p>
            <p>
                <strong>Stock Value:</strong> {{ product.calculate_total_stock_value }}
            </p>
        </div>
        <div class="col-md-6">
            <p>{{ product.product_description }}</p>
        </div>
    </div>
    <hr>
    <div>
        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Stock Date</th>
                    <th>Product Supplier</th>
                    <th>Product Quantity</th>
                    <th>Products Issued</th>
                    <th>Product Bought At</th>
                    <th>Stock Amount</th>
                </tr>
            </thead>
            <tbody>
                {% for stock in stocks %}
                <tr>
                    <td>{{ stock.date_created }}</td>
                    <td>{{ stock.product_supplier }}</td>
                    <td>{{ stock.product_quantity }}</td>
                    <td>{{ stock.products_issued }}</td>
                    <td>{{ stock.product_bought_at }}</td>
                    <td>{{ stock.product_stock_amount }}</td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    <div>
</div>
{% endblock %}

products/templates/products/update_category.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>Update Category</title>
    <!-- Include Bootstrap CSS -->
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/css/bootstrap.min.css">
</head>
<body>
    <div class="container">
        <h2>Update Category</h2>
        <form method="post" class="form">
            {% csrf_token %}
            {{ form.non_field_errors }}
            <div class="form-group">
                {{ form.category_name.label_tag }}
                {{ form.category_name }}
            </div>
            <div class="form-group">
                {{ form.category_description.label_tag }}
                {{ form.category_description }}
            </div>
            <button type="submit" class="btn btn-primary">Update Category</button>
        </form>
    </div>
    <!-- Include Bootstrap JS and jQuery if needed -->
    <script src="https://code.jquery.com/jquery-3.5.1.slim.min.js"></script>
    <script src="https://cdn.jsdelivr.net/npm/@popperjs/core@2.9.3/dist/umd/popper.min.js"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.5.2/js/bootstrap.min.js"></script>
</body>
</html>

products/templates/products/update_product.html
{% extends "products/base.html" %}
{% block title %}
    Update Product
{% endblock %}
{% block content %}
<div class="container">
    <h2>Update Product</h2>
    <form method="post" class="form">
        {% csrf_token %}
        {{ form.non_field_errors }}
        <div class="form-group">
            {{ form.product_category.label_tag }}
            {{ form.product_category }}
        </div>
        <div class="form-group">
            {{ form.product_code.label_tag }}
            {{ form.product_code }}
        </div>
        <div class="form-group">
            {{ form.product_name.label_tag }}
            {{ form.product_name }}
        </div>
        <div class="form-group">
            {{ form.product_description.label_tag }}
            {{ form.product_description }}
        </div>
        <button type="submit" class="btn btn-primary">Update Product</button>
    </form>
</div>
{% endblock %}